env:
  global:
    - secure: "bo2Pu5OcpEM5VgRYV9s7HzJySy0a0BCCF4FR1x9Jx0PEeLRRPCQ2oFTLX1k6O7nMcYXtg6/856Em3q2g69vgZCfn3IgwVKhZkBaFU5bKnDLqf/0zy2uoPOy6UEpLW/uV9fmpk8TtS410OqNRtCiCs41ev4uump+KTFds/XLdAds="
    - secure: "TGEnw+A26UhQA5LAR152EAvvZXtcui0YXHUQNbdoNuaa9tICgh5mO9pqYRc13/Ods8iP/OnAsPNlXmRC8eleLPoHnas7cE8sic4lxJyfNCyPw3upe1aTMDnObxQEfd2GxTZoixlfPlVcFMvkECZH7sjYGLhEtUu5pn/9wU/1IvA="

addons:
  sauce_connect: true

language: node_js
node_js:
  - 0.10

install:
  - npm install -g npm
  - npm install --quiet -g grunt-cli
  - npm install
  - grunt setup
