env:
  global:
    - secure: "OxoOy4Tz+pOgi1Wc0r2EctA3pppBbp8HftyEgpYo0uTvWus5TVmksZ4M5VxxOmx6lqyUG6zYwUPd4HlX/xwwdhBzp+Ba/ZtZPNteTtDG/ZhFUhIegANm7xq5CauFu0QdVBpjim3dFQfvpV8+3pui9oV38K5Z2ScKLLZrljmJKpE="
    - secure: "YFiUIpdh/UrxhcedVQvYhSrcQ2rj8JeGmZdAauRwUo7NqfMOeV1tz36q5SW9Ed0cCE0Cs/z2SyYCVe9qRdWGr5BaTzUp4JlaKz3yt3viA+2vNVhvQSUhTDdt/oS0rsUUFKrewdobl2hvlEq7+9a0NGHNaPJIdApczW/wEUqO2os="

addons:
  sauce_connect: true

language: node_js
node_js:
  - 0.10

install:
  - npm install -g npm
  - npm install --quiet -g grunt-cli
  - npm install
  - grunt setup
